seed = 0
parent_dir = "exp/breast_cancer/ddpm_tune_best"
real_data_path = "/home/cw0466/ece477-final-project/data/breast_cancer/"
model_type = "mlp"
num_numerical_features = 30
device = "cuda:0"

[model_params]
is_y_cond = true
num_classes = 2

[model_params.rtdl_params]
d_layers = [
    512,
    128,
    128,
    128,
    128,
    512,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 1000
gaussian_loss_type = "mse"
scheduler = "cosine"

[train.main]
steps = 30000
lr = 0.0003213388530545032
weight_decay = 0.0
batch_size = 256

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "one-hot"
y_policy = "default"

[sample]
num_samples = 818
batch_size = 10000
seed = 0

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
